make clean
make build

# 1v1
./halite "make -s -C . run ARG=3" "make -s -C . run ARG=4" | grep "came in rank #1"
./halite "make -s -C . run ARG=3" "make -s -C . run ARG=4" | grep "came in rank #1"
./halite "make -s -C . run ARG=3" "make -s -C . run ARG=4" | grep "came in rank #1"
./halite "make -s -C . run ARG=3" "make -s -C . run ARG=5" | grep "came in rank #1"
./halite "make -s -C . run ARG=3" "make -s -C . run ARG=5" | grep "came in rank #1"
./halite "make -s -C . run ARG=3" "make -s -C . run ARG=5" | grep "came in rank #1"
./halite "make -s -C . run ARG=3" "make -s -C . run ARG=6" | grep "came in rank #1"
./halite "make -s -C . run ARG=3" "make -s -C . run ARG=6" | grep "came in rank #1"
./halite "make -s -C . run ARG=3" "make -s -C . run ARG=6" | grep "came in rank #1"
./halite "make -s -C . run ARG=3" "make -s -C . run ARG=7" | grep "came in rank #1"
./halite "make -s -C . run ARG=3" "make -s -C . run ARG=7" | grep "came in rank #1"
./halite "make -s -C . run ARG=3" "make -s -C . run ARG=7" | grep "came in rank #1"
./halite "make -s -C . run ARG=3" "make -s -C . run ARG=8" | grep "came in rank #1"
./halite "make -s -C . run ARG=3" "make -s -C . run ARG=8" | grep "came in rank #1"
./halite "make -s -C . run ARG=3" "make -s -C . run ARG=8" | grep "came in rank #1"
echo
./halite "make -s -C . run ARG=4" "make -s -C . run ARG=3" | grep "came in rank #1"
./halite "make -s -C . run ARG=4" "make -s -C . run ARG=3" | grep "came in rank #1"
./halite "make -s -C . run ARG=4" "make -s -C . run ARG=3" | grep "came in rank #1"
./halite "make -s -C . run ARG=4" "make -s -C . run ARG=5" | grep "came in rank #1"
./halite "make -s -C . run ARG=4" "make -s -C . run ARG=5" | grep "came in rank #1"
./halite "make -s -C . run ARG=4" "make -s -C . run ARG=5" | grep "came in rank #1"
./halite "make -s -C . run ARG=4" "make -s -C . run ARG=6" | grep "came in rank #1"
./halite "make -s -C . run ARG=4" "make -s -C . run ARG=6" | grep "came in rank #1"
./halite "make -s -C . run ARG=4" "make -s -C . run ARG=6" | grep "came in rank #1"
./halite "make -s -C . run ARG=4" "make -s -C . run ARG=7" | grep "came in rank #1"
./halite "make -s -C . run ARG=4" "make -s -C . run ARG=7" | grep "came in rank #1"
./halite "make -s -C . run ARG=4" "make -s -C . run ARG=7" | grep "came in rank #1"
./halite "make -s -C . run ARG=4" "make -s -C . run ARG=8" | grep "came in rank #1"
./halite "make -s -C . run ARG=4" "make -s -C . run ARG=8" | grep "came in rank #1"
./halite "make -s -C . run ARG=4" "make -s -C . run ARG=8" | grep "came in rank #1"
echo
./halite "make -s -C . run ARG=5" "make -s -C . run ARG=3" | grep "came in rank #1"
./halite "make -s -C . run ARG=5" "make -s -C . run ARG=3" | grep "came in rank #1"
./halite "make -s -C . run ARG=5" "make -s -C . run ARG=3" | grep "came in rank #1"
./halite "make -s -C . run ARG=5" "make -s -C . run ARG=4" | grep "came in rank #1"
./halite "make -s -C . run ARG=5" "make -s -C . run ARG=4" | grep "came in rank #1"
./halite "make -s -C . run ARG=5" "make -s -C . run ARG=4" | grep "came in rank #1"
./halite "make -s -C . run ARG=5" "make -s -C . run ARG=6" | grep "came in rank #1"
./halite "make -s -C . run ARG=5" "make -s -C . run ARG=6" | grep "came in rank #1"
./halite "make -s -C . run ARG=5" "make -s -C . run ARG=6" | grep "came in rank #1"
./halite "make -s -C . run ARG=5" "make -s -C . run ARG=7" | grep "came in rank #1"
./halite "make -s -C . run ARG=5" "make -s -C . run ARG=7" | grep "came in rank #1"
./halite "make -s -C . run ARG=5" "make -s -C . run ARG=7" | grep "came in rank #1"
./halite "make -s -C . run ARG=5" "make -s -C . run ARG=8" | grep "came in rank #1"
./halite "make -s -C . run ARG=5" "make -s -C . run ARG=8" | grep "came in rank #1"
./halite "make -s -C . run ARG=5" "make -s -C . run ARG=8" | grep "came in rank #1"
echo
./halite "make -s -C . run ARG=6" "make -s -C . run ARG=3" | grep "came in rank #1"
./halite "make -s -C . run ARG=6" "make -s -C . run ARG=3" | grep "came in rank #1"
./halite "make -s -C . run ARG=6" "make -s -C . run ARG=3" | grep "came in rank #1"
./halite "make -s -C . run ARG=6" "make -s -C . run ARG=4" | grep "came in rank #1"
./halite "make -s -C . run ARG=6" "make -s -C . run ARG=4" | grep "came in rank #1"
./halite "make -s -C . run ARG=6" "make -s -C . run ARG=4" | grep "came in rank #1"
./halite "make -s -C . run ARG=6" "make -s -C . run ARG=5" | grep "came in rank #1"
./halite "make -s -C . run ARG=6" "make -s -C . run ARG=5" | grep "came in rank #1"
./halite "make -s -C . run ARG=6" "make -s -C . run ARG=5" | grep "came in rank #1"
./halite "make -s -C . run ARG=6" "make -s -C . run ARG=7" | grep "came in rank #1"
./halite "make -s -C . run ARG=6" "make -s -C . run ARG=7" | grep "came in rank #1"
./halite "make -s -C . run ARG=6" "make -s -C . run ARG=7" | grep "came in rank #1"
./halite "make -s -C . run ARG=6" "make -s -C . run ARG=8" | grep "came in rank #1"
./halite "make -s -C . run ARG=6" "make -s -C . run ARG=8" | grep "came in rank #1"
./halite "make -s -C . run ARG=6" "make -s -C . run ARG=8" | grep "came in rank #1"
echo
./halite "make -s -C . run ARG=7" "make -s -C . run ARG=3" | grep "came in rank #1"
./halite "make -s -C . run ARG=7" "make -s -C . run ARG=3" | grep "came in rank #1"
./halite "make -s -C . run ARG=7" "make -s -C . run ARG=3" | grep "came in rank #1"
./halite "make -s -C . run ARG=7" "make -s -C . run ARG=4" | grep "came in rank #1"
./halite "make -s -C . run ARG=7" "make -s -C . run ARG=4" | grep "came in rank #1"
./halite "make -s -C . run ARG=7" "make -s -C . run ARG=4" | grep "came in rank #1"
./halite "make -s -C . run ARG=7" "make -s -C . run ARG=5" | grep "came in rank #1"
./halite "make -s -C . run ARG=7" "make -s -C . run ARG=5" | grep "came in rank #1"
./halite "make -s -C . run ARG=7" "make -s -C . run ARG=5" | grep "came in rank #1"
./halite "make -s -C . run ARG=7" "make -s -C . run ARG=6" | grep "came in rank #1"
./halite "make -s -C . run ARG=7" "make -s -C . run ARG=6" | grep "came in rank #1"
./halite "make -s -C . run ARG=7" "make -s -C . run ARG=6" | grep "came in rank #1"
./halite "make -s -C . run ARG=7" "make -s -C . run ARG=8" | grep "came in rank #1"
./halite "make -s -C . run ARG=7" "make -s -C . run ARG=8" | grep "came in rank #1"
./halite "make -s -C . run ARG=7" "make -s -C . run ARG=8" | grep "came in rank #1"
echo
./halite "make -s -C . run ARG=8" "make -s -C . run ARG=3" | grep "came in rank #1"
./halite "make -s -C . run ARG=8" "make -s -C . run ARG=3" | grep "came in rank #1"
./halite "make -s -C . run ARG=8" "make -s -C . run ARG=3" | grep "came in rank #1"
./halite "make -s -C . run ARG=8" "make -s -C . run ARG=4" | grep "came in rank #1"
./halite "make -s -C . run ARG=8" "make -s -C . run ARG=4" | grep "came in rank #1"
./halite "make -s -C . run ARG=8" "make -s -C . run ARG=4" | grep "came in rank #1"
./halite "make -s -C . run ARG=8" "make -s -C . run ARG=5" | grep "came in rank #1"
./halite "make -s -C . run ARG=8" "make -s -C . run ARG=5" | grep "came in rank #1"
./halite "make -s -C . run ARG=8" "make -s -C . run ARG=5" | grep "came in rank #1"
./halite "make -s -C . run ARG=8" "make -s -C . run ARG=6" | grep "came in rank #1"
./halite "make -s -C . run ARG=8" "make -s -C . run ARG=6" | grep "came in rank #1"
./halite "make -s -C . run ARG=8" "make -s -C . run ARG=6" | grep "came in rank #1"
./halite "make -s -C . run ARG=8" "make -s -C . run ARG=7" | grep "came in rank #1"
./halite "make -s -C . run ARG=8" "make -s -C . run ARG=7" | grep "came in rank #1"
./halite "make -s -C . run ARG=8" "make -s -C . run ARG=7" | grep "came in rank #1"

./halite "make -s -C . run ARG=6" "make -s -C . run ARG=8" | grep "came in rank #1"
./halite "make -s -C . run ARG=6" "make -s -C . run ARG=8" | grep "came in rank #1"
./halite "make -s -C . run ARG=6" "make -s -C . run ARG=8" | grep "came in rank #1"
./halite "make -s -C . run ARG=6" "make -s -C . run ARG=8" | grep "came in rank #1"
./halite "make -s -C . run ARG=6" "make -s -C . run ARG=8" | grep "came in rank #1"
./halite "make -s -C . run ARG=6" "make -s -C . run ARG=8" | grep "came in rank #1"
./halite "make -s -C . run ARG=6" "make -s -C . run ARG=8" | grep "came in rank #1"
./halite "make -s -C . run ARG=6" "make -s -C . run ARG=8" | grep "came in rank #1"
./halite "make -s -C . run ARG=6" "make -s -C . run ARG=8" | grep "came in rank #1"
./halite "make -s -C . run ARG=6" "make -s -C . run ARG=8" | grep "came in rank #1"

./halite "make -s -C . run ARG=8" "make -s -C . run ARG=6" | grep "came in rank #1"
./halite "make -s -C . run ARG=8" "make -s -C . run ARG=6" | grep "came in rank #1"
./halite "make -s -C . run ARG=8" "make -s -C . run ARG=6" | grep "came in rank #1"
./halite "make -s -C . run ARG=8" "make -s -C . run ARG=6" | grep "came in rank #1"
./halite "make -s -C . run ARG=8" "make -s -C . run ARG=6" | grep "came in rank #1"
./halite "make -s -C . run ARG=8" "make -s -C . run ARG=6" | grep "came in rank #1"
./halite "make -s -C . run ARG=8" "make -s -C . run ARG=6" | grep "came in rank #1"
./halite "make -s -C . run ARG=8" "make -s -C . run ARG=6" | grep "came in rank #1"
./halite "make -s -C . run ARG=8" "make -s -C . run ARG=6" | grep "came in rank #1"
./halite "make -s -C . run ARG=8" "make -s -C . run ARG=6" | grep "came in rank #1"

make clean